version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: docproc-postgres-prod
    environment:
      POSTGRES_DB: docproc
      POSTGRES_USER: ${POSTGRES_USER:-docproc_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-docproc_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - docproc-network-prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-docproc_user}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis
  redis:
    image: redis:7-alpine
    container_name: docproc-redis-prod
    ports:
      - "6379:6379"
    networks:
      - docproc-network-prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Server
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.prod
    container_name: docproc-api-prod
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-docproc_user}:${POSTGRES_PASSWORD:-docproc_password}@postgres:5432/docproc
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      REDIS_URL: redis://redis:6379
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - docproc-network-prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web App
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.prod
    container_name: docproc-web-prod
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - docproc-network-prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: docproc-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
      - api
    networks:
      - docproc-network-prod
    restart: unless-stopped

volumes:
  postgres_data_prod:

networks:
  docproc-network-prod:
    driver: bridge
